# NUMPY PRACTICE

In [2]:
#1D array
import numpy as np
n1=np.array([10,20,32,32,4,2,3,12,12])
n1

array([10, 20, 32, 32,  4,  2,  3, 12, 12])

In [9]:
#2D ARRAY
n2=np.array([[i for i in range(23,99,4)],[i for i in range(99,23,-4)]])
n2

array([[23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83,
        87, 91, 95],
       [99, 95, 91, 87, 83, 79, 75, 71, 67, 63, 59, 55, 51, 47, 43, 39,
        35, 31, 27]])

In [12]:
type(n1)

numpy.ndarray

In [16]:
# array of zeros 
n3=np.zeros((5,5))
print(n3)
# array of ones
n4=np.ones((3,3))
n4

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# array of same no
ns=np.full((4,4),10)
nf=np.full((6,9),6)
print(ns,nf)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] [[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]


In [21]:
# arrray of arange
na=np.arange(10,100,5)
naa=np.arange(10,40)
print(naa)
na

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [26]:
# array oof random no
from random import*
nr=np.random.randint(1,101,20)
nr1=np.random.randint(0,100,40)
print(nr)
print(nr1)


[55 94 76  9 40 43 36 28 44 95 25 16 36 27 98 88 79  2 88 96]
[92 14 14 48 56 32  3 41  3  9 89 42 11 51 31 31 53 19 74 78  0 22 71 79
 46  0 49  0 45 37 26 65 69 73 75 56 96 12  8 64]


In [30]:
# changin shape 
ns=np.full((4,4),10)
nf=np.full((6,9),6)
print(ns,nf)
ns.shape=(2,8)
ns.shape
ns

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] [[6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6]]


array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [34]:
# stack 
v1=np.arange(2,8)
v2=np.arange(8,2,-1)
#vertical stack
v=np.vstack((v1,v2))
print("VERTICAL STACK")
print(v)
#horizontal stack
h=np.hstack((v1,v2))
print("HORIZONTAL stack")
print(h)
# column stack
print("COLUMN STACK")
c=np.column_stack((v1,v2))
print(c)


VERTICAL STACK
[[2 3 4 5 6 7]
 [8 7 6 5 4 3]]
HORIZONTAL stack
[2 3 4 5 6 7 8 7 6 5 4 3]
COLUMN STACK
[[2 8]
 [3 7]
 [4 6]
 [5 5]
 [6 4]
 [7 3]]


# intersection diffrence etc



In [37]:
a1=np.random.randint(2,100,20)
a2=np.random.randint(2,50,20)
# diffrence
print("DIFFRENCE")
d1=np.setdiff1d(a1,a2)
print(d1)
d2=np.setdiff1d(a2,a1)
print(d2)
#INTERSECTIONS
print("INTERSECTION")
i1=np.intersect1d(a1,a2)
print(i1)
i2=np.intersect1d(a2,a1)
print(i2)

DIFFRENCE
[ 2 14 20 21 30 34 38 44 48 51 55 61 63 69 89 93 95]
[ 4  5  7 10 15 17 18 26 28 36 40 42 45 47 49]
INTERSECTION
[ 3 27 32]
[ 3 27 32]


In [40]:
# SUMMING OF ARRAY
a1=np.random.randint(2,100,20)
a2=np.random.randint(2,50,20)
print(a1)
print(a2)
print("SUMMING OF ARRAYS")
# to add elenment of the two ary od same index
summ=np.sum([a1,a2],axis=0)
print(summ)
# to add the all the aemelenet of an array
sum1=np.sum([a1,a2],axis=1)
print(sum1)


[90  7 56 64 46 95 50 54 81 53 44 73 38 10 76 39 72 81 85 25]
[45 38 29 16 45 11 31  4 42  9  8 34 47 33 44 49 18 35  4 12]
SUMMING OF ARRAYS
[135  45  85  80  91 106  81  58 123  62  52 107  85  43 120  88  90 116
  89  37]
[1139  554]


In [43]:
# mathematical operraton of array
#1ADDiITON
a=np.arange(2,20,2)
print(a)
print(a+1)
print(a-1)
print(a*2)
print(a/2)



[ 2  4  6  8 10 12 14 16 18]
[ 3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17]
[ 4  8 12 16 20 24 28 32 36]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [49]:
# MEAN MEDIAN MODE
arr=np.arange(0,50,3)
print(arr)
print("mean",np.mean(arr))
print("mode",np.median(arr))
print("std",f"{ np.std(arr)}")


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
mean 24.0
mode 24.0
std 14.696938456699069


In [50]:
# saving and loading
arr=np.arange(0,50,3)
np.save("mynumpy",arr)
print(arr)
nload=np.load("mynumpy.npy")
print(nload)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
